components:
  schemas:
    AggregationResponse:
      properties:
        count:
          format: int64
          type: integer
        key:
          type: string
      type: object
    ByBoundingBox:
      properties:
        bottomRight:
          $ref: '#/components/schemas/Point'
        topLeft:
          $ref: '#/components/schemas/Point'
      required:
      - bottomRight
      - topLeft
      type: object
    ByDistance:
      properties:
        distance:
          format: double
          maximum: 9223372036854775807
          type: number
        point:
          $ref: '#/components/schemas/Point'
      required:
      - point
      type: object
    ByGeoPolygon:
      properties:
        points:
          items:
            $ref: '#/components/schemas/Point'
          type: array
      required:
      - points
      type: object
    ByIntersection:
      properties:
        polygons:
          items:
            $ref: '#/components/schemas/Polygon'
          type: array
      required:
      - polygons
      type: object
    ByWithinPolygon:
      properties:
        points:
          items:
            $ref: '#/components/schemas/Point'
          type: array
      required:
      - points
      type: object
    ConnectedOuterService:
      properties:
        name:
          type: string
        version:
          type: string
      type: object
    CursorQueryRequest:
      properties:
        cursor:
          type: string
        kind:
          type: object
        limit:
          format: int32
          minimum: 0
          type: integer
        query:
          type: string
        queryAsOwner:
          type: boolean
        returnedFields:
          items:
            type: string
          type: array
        sort:
          $ref: '#/components/schemas/SortQuery'
        spatialFilter:
          $ref: '#/components/schemas/SpatialFilter'
        trackTotalCount:
          type: boolean
      required:
      - kind
      type: object
    CursorQueryResponse:
      properties:
        cursor:
          type: string
        results:
          items:
            additionalProperties:
              type: object
            type: object
          type: array
        totalCount:
          format: int64
          type: integer
      type: object
    Point:
      properties:
        latitude:
          format: double
          maximum: 90
          minimum: -90
          type: number
        longitude:
          format: double
          type: number
      type: object
    Polygon:
      properties:
        points:
          items:
            $ref: '#/components/schemas/Point'
          type: array
      type: object
    QueryRequest:
      properties:
        aggregateBy:
          type: string
        kind:
          type: object
        limit:
          format: int32
          minimum: 0
          type: integer
        offset:
          format: int32
          minimum: 0
          type: integer
        query:
          type: string
        queryAsOwner:
          type: boolean
        returnedFields:
          items:
            type: string
          type: array
        sort:
          $ref: '#/components/schemas/SortQuery'
        spatialFilter:
          $ref: '#/components/schemas/SpatialFilter'
        trackTotalCount:
          type: boolean
      required:
      - kind
      type: object
    QueryResponse:
      properties:
        aggregations:
          items:
            $ref: '#/components/schemas/AggregationResponse'
          type: array
        results:
          items:
            additionalProperties:
              type: object
            type: object
          type: array
        totalCount:
          format: int64
          type: integer
      type: object
    SortQuery:
      properties:
        field:
          items:
            type: string
          type: array
        order:
          items:
            enum:
            - ASC
            - DESC
            type: string
          type: array
      type: object
    SpatialFilter:
      properties:
        byBoundingBox:
          $ref: '#/components/schemas/ByBoundingBox'
        byDistance:
          $ref: '#/components/schemas/ByDistance'
        byGeoPolygon:
          $ref: '#/components/schemas/ByGeoPolygon'
        byIntersection:
          $ref: '#/components/schemas/ByIntersection'
        byWithinPolygon:
          $ref: '#/components/schemas/ByWithinPolygon'
        field:
          type: string
      required:
      - field
      type: object
    VersionInfo:
      properties:
        artifactId:
          type: string
        branch:
          type: string
        buildTime:
          type: string
        commitId:
          type: string
        commitMessage:
          type: string
        connectedOuterServices:
          items:
            $ref: '#/components/schemas/ConnectedOuterService'
          type: array
        groupId:
          type: string
        version:
          type: string
      type: object
  securitySchemes:
    Authorization:
      bearerFormat: Authorization
      scheme: bearer
      type: http
info:
  description: Search service that provides a set of APIs to search records against
    Elasticsearch
  title: Search Service
  version: '1.0'
openapi: 3.0.1
paths:
  /:
    get:
      operationId: whoami_1
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - whoami-controller
  /health/liveness_check:
    get:
      operationId: livenessCheck
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - health-check-api
  /health/readiness_check:
    get:
      operationId: readinessCheck
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - health-check-api
  /info:
    get:
      operationId: info
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
          description: OK
      tags:
      - info-api
  /query:
    post:
      operationId: queryRecords
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QueryResponse'
          description: OK
      tags:
      - search-api
  /query_with_cursor:
    post:
      operationId: queryWithCursor
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CursorQueryRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CursorQueryResponse'
          description: OK
      tags:
      - search-api
  /whoami:
    get:
      operationId: whoami
      parameters:
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - whoami-controller
security:
- Authorization: []
servers:
- url: /api/search/v2
